import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./Navbar/page";
import Particles from "@/components/Particles";
import { Amiri } from 'next/font/google';

export const amiri = Amiri({
  subsets: ['latin', 'arabic'], // Sesuaikan subset yang diperlukan
  weight: ['400', '700'],       // Sesuaikan bobot font yang diperlukan
  style: ['normal', 'italic'],  // Sesuaikan gaya yang diperlukan
  variable: '--font-amiri',     // Definisikan variabel CSS
  display: 'swap',
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${amiri.variable}  antialiased`}>
        {/* BACKGROUND LAYER: Tetap di belakang saat scroll */}
        <div className="fixed inset-0 z-0 overflow-hidden bg-slate-950">
          <div style={{ width: "100%", height: "600px", position: "relative" }}>
            <Particles
              particleColors={["#2fe9e6"]}
              particleCount={200}
              particleSpread={10}
              speed={0.1}
              particleBaseSize={100}
              moveParticlesOnHover
              alphaParticles={false}
              disableRotation={false}
              pixelRatio={1}
            />
          </div>
        </div>

        {/* NAVBAR: Pastikan z-index lebih tinggi dari background */}
        <nav className="relative z-50">
          <Navbar />
        </nav>
        <main className="relative z-10 min-h-screen px-10 text-white">
          {children}
        </main>
      </body>
    </html>
  );
}
