import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'
import Particles from "@/components/Particles";
import { Amiri } from "next/font/google";
import FooterComponent from "@/components/footer";
import Navbar from "./Navbar/page";

export const amiri = localFont({
  src : "../public/fontUts.otf",
  // Sesuaikan gaya yang diperlukan
  variable: "--font-amiri", // Definisikan variabel CSS
  display: "swap",
});

export const metadata: Metadata = {
  title: "Web Islami",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${amiri.variable}  antialiased`}>
        {/* BACKGROUND LAYER: Tetap di belakang saat scroll */}
        <div className="fixed inset-0 z-0 overflow-hidden bg-slate-950">
          <div style={{ width: "100%", height: "600px", position: "relative" }}>
            <Particles
              particleColors={["#2fe9e6"]}
              particleCount={200}
              particleSpread={10}
              speed={0.1}
              particleBaseSize={100}
              moveParticlesOnHover
              alphaParticles={false}
              disableRotation={false}
              pixelRatio={1}
            />
          </div>
        </div>
      {/* 
        <header>
          <Navbar />
        </header>
*/}
        <main className="relative z-10  text-white">{children}</main>
        <footer className="relative">
          <FooterComponent />
        </footer>
      </body>
    </html>
  );
}
